language: node_js
node_js:
  - "5.0"
 # - 0.10.36

env:
  global:
    - region="us-east-1"
    - secure: "T6MBAHfZdRt/nJ7KetChiD3vP3ueFAzXsPGBljhVkSmKs6ZWdaZK27Ximfehyx7omnKC1B+2xYIL2P1SAn9TQAsXbdLXVLrNRNUPfFL5LFcymyYIUHRG80IKlISeQ/Cq7sBmD7BqdXH9jog4VKw868B0jytMdPQSQoVFFXV1Rp3JP1eGuS19FghZ6gtpUgw/O1QcU3NbxvEwTZq2DgpwLyjUPogEqYOoufbrOA0Ik56n6C8o/sUEVAuDMBzsLyRY53oj/NXCVOn05U6ob96t22nkVp0Z/UHZqRbhCHwCBf0XUFw1wpJ+4r+JE+pDsXnLyuCuGnd6ze1ASguLN2B5FzAPeD7vA+QwkjsfOhT+AxX+66y0FZ25bywStbTosesygq/EWRKY2Glh7CFkqxZs9El0/kp4A103lNaAYsMKECphSvRUe6TetfUehO9+zEKBzF+gqlvVIn3/tesDa2kdJTqIreWDBPspiSb0kejjIl1KLvpdVXKRKR96fdjxg+wXmzLP0NgNd9kavUbHafilih+3lgRMb3b5JjAX8evCZvgqGG793dM8hwOn9kQbGflJvZi9nC5tXOQYy6EfAwMH8H9rodCx/W7vayMe+HdaGDH/pHxu+EQSQ+hr57Z6vM4GmIq9NXWNFOgkiBpE3cX5DTmtoDxC14jgakY84oMCbx0="
    - secure: "TLxU6rzJLlTW9H0+ThfkIrY6aWl40CwTaBsZm8T2Qa7HizmRP9LnukMmVcuQX58RKUHYDnPWUszaefoSpdeMSCpVQGmkoBrbArzP5USu0yrrPJSTw3IUEmbZzihv1rjmYyn7o6/O3zZISC+8qRHZUZHfwmIuqhgeRy9lL3NoLqfszPJwinBXQ8lYapV/+lnvyRrKqnaCbf4LL81CPY5BNc+7Rwfq/teIhFFobiVhwk03rOnfWO4Pe2jntUAEvicROhIZhvbusMGLYqQd0blFV1OZ9nknlYVtPsSw1h7hQwiecjTSHnQ5P9wSgndL/1TBalQOajkwl16zc5hBVBRNNDMMVJM1Dc/M987JJP6B+CEPYKC/Mq1lpdbPMCT1s7yE1ZX2GnJIdOQpPeDzTt2jh3aO6/t4FraiVzJEkDIEaXJXpBWiWe2jh68YvjtmodrhrqV5yPq1ZcfiuziXJA+zddmhPCkGMRbYFGL5s2FaHme8plsI+nOTfzJj/p6xGfQfHtwIOei37wDV3eX12I83IrvQICdAu3+JKCkB4DhWxtxlS0tNKldH6Z447lOUtXHk2JjgmUWliCoATd3/OkuhWQvLEojCEdVZ+r19tDc9iBgg+4vPBDn+erZE9yO7Cpgwo/7b0pqjaAkZ85nLpE4PIpfkt0uxOtXW8ok0iYr30Dw="

install:
  - npm install -g gulp mocha
  - npm install
  - gulp deploy_stage

after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. Current branch is $TRAVIS_BRANCH"; exit 0; fi
  - echo {\"buildNumber\":\"$TRAVIS_BUILD_NUMBER\"} > backend/buildNumber.json
  - gulp deploy_prod
