# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.11.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
      - run:
            name: Running tests
            command: |
                  curl -o terraform.zip https://releases.hashicorp.com/terraform/{$TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
                  unzip terraform.zip
                  chmod +x terraform
                  export PATH=$(pwd):$PATH
                  terraform --version
                  npm run webpack
                  npm run tf:init
                  npm run tf:apply

