version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "package.json" }}
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: REGION=us-east-1 npm test
      - run:
            name: Install Terraform
            command: |
                  curl -o terraform.zip https://releases.hashicorp.com/terraform/{$TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
                  unzip terraform.zip
                  chmod +x terraform
                  export PATH=$(pwd):$PATH
                  terraform --version
                  npm run webpack
                  npm run tf:init
                  TF_VAR_commitdid=CIRCLE_SHA1 TF_VAR_version=CIRCLE_BUILD_NUM npm run tf:apply
                  npm run frontend

